ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LOGIN_2FA_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TWO_FACTOR_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TWO_FACTOR_DISABLED';

ALTER TABLE "User"
ADD COLUMN "twoFactorSecret" TEXT,
ADD COLUMN "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "twoFactorEnabledAt" TIMESTAMP(3);
